### ISSUE TITLE
Not require two side panels, specify just [left | right]

### ISSUE THREAD

**Issue by cgudea** [discord/OverlappingPanels#17]
I'm a huge fan of this library's UX as the Android 10 back gesture breaks most app's UX in regards to side "panels"/navigation drawers.

I'm curious if there are any plans to make it possible to only need one overlapped panel instead of the currently required *Start* and *End* panels. I'd like to use this as a drop in replacement for all my navigation drawers but rarely do I need both start + end panels/drawers.

Cheers!

**Comment by itsnotashes** [comment]
+1 

It would be nice to have this feature for just one navigation panel!

**Comment by thementalgoose** [comment]
Correct me if i'm wrong but I think you can? Just have a blank frame layout and use [`setEndPanelLockState(LockState.CLOSED)`](https://github.com/discord/OverlappingPanels/blob/master/overlapping_panels/src/main/java/com/discord/panels/OverlappingPanelsLayout.kt#L351) to keep it permanently closed 👍

**Comment by sivaprakashsj** [comment]
> Correct me if i'm wrong but I think you can? Just have a blank frame layout and use [`setEndPanelLockState(LockState.CLOSED)`](https://github.com/discord/OverlappingPanels/blob/master/overlapping_panels/src/main/java/com/discord/panels/OverlappingPanelsLayout.kt#L351) to keep it permanently closed 👍

It's working!
